### PR TITLE
📓 Added hungarian translation

### PR DESCRIPTION
**Pull request by KristofKekesi**

### CODE REVIEW

**Review by dpaulino — APPROVED** [review]

**Review by dpaulino — CHANGES_REQUESTED** [review]
Just noticed that the csproj file wasn't edited. Did you add this resw file using vs2019? We need the csproj edited to recognize this file.

**Comment by dpaulino** [comment]
Here's an example of how the csproj is edited for a new resw https://github.com/jenius-apps/ambie/pull/31/files

**Comment by KristofKekesi** [comment]
So I updated csproj with a new commit.

**Review by dpaulino — APPROVED** [review]

**Comment by dpaulino** [comment]
Thanks!

**Pull request merged**
