### PR TITLE
Improve Persian translation

### PR DESCRIPTION
**Pull request by rezaroointan**
Update Persian [fa] translation

### CODE REVIEW

**Comment by dpaulino** [comment]
thank you for starting the PR! Can you also take a look at the Persian entries here and see if anything can be improved? https://github.com/jenius-apps/ambie/blob/main/src/AmbientSounds.Uwp/Assets/Data.json

**Comment by dpaulino** [comment]
Some strings were removed, which caused conflicts in your PR. Can you get the latest main branch changes?

**Comment by dpaulino** [comment]
Thank you for your contribution!

**Comment by rezaroointan** [comment]
I thank you too 🙂

**Pull request merged**
