### PR TITLE
Added French translation (Ajout de la traduction française) 

### PR DESCRIPTION
**Pull request by faouziMohamed**
# Hello world
- Here is a proposal for a French translation (fr and fr-FR)  
- Below a screenshot for quick preview  

Ambie screenshoot

### CODE REVIEW

**Review by dpaulino — CHANGES_REQUESTED** [review]
Thank you very much for the french translation! Any chance we can remove the gif though? Looking forward to merging your translations soon!

**Comment by dpaulino** [comment]
Thanks for the update! Can you merge the latest updates from main? I think there are some updates

**Comment by faouziMohamed** [comment]
Merge done!

**Review by dpaulino — APPROVED** [review]

**Comment by dpaulino** [comment]
Thank you so much for the translation!

**Comment by faouziMohamed** [comment]
Welcome !

**Pull request merged**
