### PR TITLE
Added danish (da-DK) translations

### PR DESCRIPTION
**Pull request by byrialsen**
Added danish translations.

### CODE REVIEW

**Comment by dpaulino** [comment]
Resolves #65

**Comment by dpaulino** [comment]
Thank you for the translation! Please don't forget to update the readme to add you as a translator

**Review by dpaulino — APPROVED** [review]
Looks good, but let me know if you want to update the readme. If not, we can merge right away

**Comment by byrialsen** [comment]
I have updated the README.md.

**Comment by daswareinfach** [comment]
looks great

**Review by dpaulino — APPROVED** [review]

**Comment by dpaulino** [comment]
@byrialsen can you try pulling the latest changes from the main branch? I think there a couple small changes in the translation strings

**Review by dpaulino — APPROVED** [review]
Awesome, thank you!

**Comment by byrialsen** [comment]
You're welcome 👍

**Pull request merged**
