### PR TITLE
Enable ComputeSharp screensaver on Xbox Series S and X

### PR DESCRIPTION
**Pull request by Sergio0694**
This PR enables the ComputeSharp-powered animated screensavers on Xbox Series S and X. This is possible because UWP apps running on the new consoles can use DX12 APIs with the necessary feature set that allows ComputeSharp to work. The PR also includes a new system information API that's used to detect when the device is an Xbox One, so the feature can remain disabled there.

### CODE REVIEW

**Comment by rudyhuyn** [comment]
great job!

**Review by rudyhuyn — APPROVED** [review]

**Comment by sowenzhang** [comment]
image

approve!

**Comment by JustinXinLiu** [comment]
Please merge!

**Comment by dpaulino** [comment]
Please test on an xbox and share screenshots/videos

**Comment by Sergio0694** [comment]
@dpaulino Dude I don't have an Xbox ughhhhhhh 🤣

**Comment by itsWindows11** [comment]
~~Looks like this will never be merged.~~

**Pull request closed without merging**
