### PR TITLE
Updated Polish translations

### PR DESCRIPTION
**Pull request by maciej-klupp**
Updated Polish translations. Some strings were too long and were cut off in the app.

### CODE REVIEW

**Comment by dpaulino** [comment]
Can you post a few screenshots of before and after?

**Comment by dpaulino** [comment]
Screenshots will also help me understand if I should change some areas to better handle longer text

**Comment by maciej-klupp** [comment]
I am unfortunately not familiar with how compiling apps works, so while I can't provide a screenshot of how the app looks after the changes, I can provide a mock-up of how it should look like. I hope this is OK.

Those two elements highlighted in red were mainly affected. 
### BEFORE CHANGES (HOW THE APP LOOKS NOW)
PL_LONG

### AFTER CHANGES (MOCK-UP)
image

I originally translated "Get Ambie Plus" as "_Kup subskrypcję Ambie Plus_" which means "**Get Ambie Plus subscription**". Sticking to just "_Kup Ambie Plus_", which means "**Buy Ambie Plus**" is clear enough and fits with the character limit.

I mistranslated the strings under the first two counters. Nevertheless, the most direct Polish equivalents ("_Koncentracja_" or "_Skupienie_" for "**Focus**", "_Odpoczynek_" for "**Rest**" and "_Powtórzenia_" for "**Repeats**") are still longer than the space provided.
I managed to find words which have similar meaning ("_Praca_" which means "**work**", "_Przerwa_" which means "**Break**" and "_Cykle_" which means "**Cycles**") which also fit in the character limit. These shortened forms  are clear and in my opinion understandable to a Polish speaking person, so no meaning is lost.

If the spacing in these counters could be changed to allow for longer descriptions that would be fantastic and it would allow for those longer, more direct Polish translations to be used. Something along those lines:

### PROPOSED CHANGES (MOCK-UP)
image

While this would make less configurations visible, maybe some sort of scroll bar or arrows could be introduced to browse between the saved configurations. I am not a programmer and I'm not sure how difficult such a thing would be to implement.

**Comment by dpaulino** [comment]
thank you for the screenshots!
> If the spacing in these counters could be changed to allow for longer descriptions that would be fantastic and it would allow for those longer, more direct Polish translations to be used. Something along those lines:

I actually already fixed this! I'm reducing the size of the text so that longer strings will fit. Here's Polish:
image


The next update should be coming Friday at the latest. I recommend reverting the changes for these counters, but keeping the change for Buy Ambie Plus

**Comment by maciej-klupp** [comment]
I updated the translation according to your instructions.

**Pull request merged**
