### PR TITLE
Added czech translation

### PR DESCRIPTION
**Pull request by MichalMoudry**
Note:

- Fireplace is translated to "Krb" and "b" in the word is hard to read (it overlaps with fire image).
ambie-fireplace-image
- I am not the best in my native language, so be aware of that (some of the stuff isn't translated word for word like "Contact the creator" is translated as "Contact the author of the application").

### CODE REVIEW

**Comment by dpaulino** [comment]
@MichalMoudry thanks for the translation! Looks like you have some pr conflicts though. I'll review once they've been resolved.

**Comment by MichalMoudry** [comment]
Resolved conficts in .csproj file and hopefully it will work.

**Comment by dpaulino** [comment]
@MichalMoudry is there still a readability issue with `Krb`? can you post a new screenshot? There should be some fluent material that makes this readable, like this:
image

**Comment by dpaulino** [comment]
Just checked myself. Looks good! 
image

**Review by dpaulino — APPROVED** [review]

**Comment by dpaulino** [comment]
Thank you for the translation!

**Pull request merged**
